repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.60.3
    hooks:
      - id: golangci-lint

  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: markdownlint-cli2
        language: system
        types: [markdown]
        files: \.md$
        args: ["--config", ".markdownlint.yml"]
