[Default.bindings]
d = "deleteTrack"
a = "addToQueue"
Q = "quit"
# leader key
SPC = "openCommandPalette"

[Global.bindings]
ESC = "closeModal"
CTRL-C = "copy"
CTRL-V = "paste"
CTRL-X = "cut"
CTRL-Z = "undo"

[Empty.bindings]
# context with no bindings

[Modal.bindings]
context_override = "Empty"
ESC = "closeModal"
enter = "confirmAction"
n = "nextOption"
p = "previousOption"

[TextField.bindings]
context_override = "Empty"
enter = "submitText"
ESC = "cancelInput"
CTRL-U = "clearText"

[ArticlePreset.bindings]
a = "queue.AddTrack"
A = "playlists.AddTrackToPlaylist"
y = "favoriteTrack toggle"

[SearchPreset.bindings]
"/" = "search"

[ListPreset.bindings]
g = "goToTop"
G = "goToBottom"

[Queue.bindings]
context_add = "ArticlePreset,ListPreset"
d = "queue.deleteTrack"
m = "queue.moveTrack"
s = "shuffleQueue"

[Playlist.bindings]
context_add = "ListPreset"
n = "playlistman.New"
r = "playlistman.Rename"
D = "playlistman.Delete"
a = "playlist.Play"
s = "playlist.ShufflePlay"

[Playlist.TrackList.bindings]
context_add = "ArticlePreset,ListPreset"
d = "playlist.deleteTrack"

[Browser.bindings]
context_add = "ArticlePreset,SearchPreset"
S = "shufflePlay"
v = "viewArtist"
a = "addArtistToQueue; cursorDown"

[Browser.AlbumList.bindings]
context_add = "ArticlePreset"
a = "addAlbumToQueue; cursorDown"
