name: CI

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    branches:
      - main
      - "release/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Debian Stable's + the two supported Go versions
        go-version: [1.19, 1.22, 1.23]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Validate TOML syntax
        run: |
          if command -v toml-validator &> /dev/null
          then
            toml-validator example.toml
          else
            go install github.com/BurntSushi/toml/cmd/tomlv@v1.4.0
            tomlv example.toml
          fi

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Run race detector
        run: go test -race -v ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3

      - name: Generate coverage report
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: coverage.out
          flags: unittests
          fail_ci_if_error: true
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
